"""models refactoingr

Revision ID: 8d9ce63abd70
Revises: 
Create Date: 2025-03-09 21:31:37.789546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9ce63abd70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('ADMIN', 'DRIVER', 'CUSTOMER', name='userrole'), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'CANCELED', name='bookingstatus'),
               nullable=False)
        batch_op.drop_constraint('unique_seat_booking', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=128), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ADMIN', 'DRIVER', 'CUSTOMER', name='userrole'),
               existing_nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'DRIVER', 'CUSTOMER', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('_password_hash')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_seat_booking', ['bus_id', 'seat_number'])
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'CANCELED', name='bookingstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('role')

    # ### end Alembic commands ###
